name: Publish To NPM

on: 
    push:
        branches: [master, main]
    pull_request:
        branches: [master, main]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 18.x
              uses: actions/setup-node@v1
              with:
                  node-version: 18.x
                  registry-url: https://registry.npmjs.org/
            - name: Install Dependencies
              run: npm i
            - name: Build
              run: npm run build
            - name: Publish To NPM
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
